# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nimbu < Formula
  desc "CLI for the Nimbu API"
  homepage "https://github.com/nimbu/nimbu-go-cli"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nimbu/cli/releases/download/v0.1.6/nimbu_0.1.6_darwin_amd64.tar.gz"
      sha256 "ff186291165b445e644bdbfde6146676dbe7055a2ceca031acf2db83f544ee67"

      define_method(:install) do
        bin.install "nimbu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nimbu/cli/releases/download/v0.1.6/nimbu_0.1.6_darwin_arm64.tar.gz"
      sha256 "7a97379411267e3babe0c929a47c1267ee6160bfdd4bab60f5273df6ac34ffdc"

      define_method(:install) do
        bin.install "nimbu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nimbu/cli/releases/download/v0.1.6/nimbu_0.1.6_linux_amd64.tar.gz"
      sha256 "ba5719eecf6a30fcd4e764146b8ef7f4ba668fb80378f6eb2e1def4d1178a685"
      define_method(:install) do
        bin.install "nimbu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nimbu/cli/releases/download/v0.1.6/nimbu_0.1.6_linux_arm64.tar.gz"
      sha256 "56538c81b27087c1dd7186748a01d1e6e9c8fb5b52ed0c598d7c48e719daf35d"
      define_method(:install) do
        bin.install "nimbu"
      end
    end
  end

  test do
    system "#{bin}/nimbu", "version"
  end
end
