# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nimbu < Formula
  desc "CLI for the Nimbu API"
  homepage "https://github.com/nimbu/nimbu-go-cli"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nimbu/cli/releases/download/v0.1.4/nimbu_0.1.4_darwin_amd64.tar.gz"
      sha256 "e19e5e1a93970c06f6dc7f64f557cd8b5de09315f9f52fabb4a9c106134fea5a"

      define_method(:install) do
        bin.install "nimbu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nimbu/cli/releases/download/v0.1.4/nimbu_0.1.4_darwin_arm64.tar.gz"
      sha256 "056904947dcd2a014271f6721900c1e1a4d49c1e077292b8e762866fc73d0143"

      define_method(:install) do
        bin.install "nimbu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nimbu/cli/releases/download/v0.1.4/nimbu_0.1.4_linux_amd64.tar.gz"
      sha256 "d4aff91581cd0a418e41e0ae6500289fdc2966c246e1a65e27ad695295add115"
      define_method(:install) do
        bin.install "nimbu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nimbu/cli/releases/download/v0.1.4/nimbu_0.1.4_linux_arm64.tar.gz"
      sha256 "f7c3289ed2fa24c174964258df8988539b33db2d45826dc11568eac261cccea8"
      define_method(:install) do
        bin.install "nimbu"
      end
    end
  end

  test do
    system "#{bin}/nimbu", "version"
  end
end
