# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nimbu < Formula
  desc "CLI for the Nimbu API"
  homepage "https://github.com/nimbu/nimbu-go-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nimbu/cli/releases/download/v0.1.3/nimbu_0.1.3_darwin_amd64.tar.gz"
      sha256 "145c0af12ad57afc55e82fcf3621fab6625ffce34f155d5f83e7438a344bca23"

      define_method(:install) do
        bin.install "nimbu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nimbu/cli/releases/download/v0.1.3/nimbu_0.1.3_darwin_arm64.tar.gz"
      sha256 "5a8a94657e0c89a8ec7190d13dfce749dfe1a8c5723705b50fb952d46dea498c"

      define_method(:install) do
        bin.install "nimbu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nimbu/cli/releases/download/v0.1.3/nimbu_0.1.3_linux_amd64.tar.gz"
      sha256 "8b3fde67cd993a0a5827623b7aaaee10af046fd3a851b7e68f4688f2db204484"
      define_method(:install) do
        bin.install "nimbu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nimbu/cli/releases/download/v0.1.3/nimbu_0.1.3_linux_arm64.tar.gz"
      sha256 "19f05cfdd62da00138fb804cd49eee073f0da933de784191e2cbe77b293cf27b"
      define_method(:install) do
        bin.install "nimbu"
      end
    end
  end

  test do
    system "#{bin}/nimbu", "version"
  end
end
